apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: go-tqunqyfv
  janus-idp.io/tekton: go-tqunqyfv
  backstage.io/kubernetes-id: go-tqunqyfv
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: go-tqunqyfv
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
